version: '2'
services:
    apache-php:
        build:
            context: ./build/apache-php
            dockerfile: Dockerfile
            args:
                - WWW_SERVERNAME=${WWW_SERVERNAME}
                - WWW_DOCUMENT_ROOT=${WWW_DOCUMENT_ROOT}
                - API_SERVERNAME=${API_SERVERNAME}
                - API_DOCUMENT_ROOT=${API_DOCUMENT_ROOT}
                - ADMIN_SERVERNAME=${ADMIN_SERVERNAME}
                - ADMIN_DOCUMENT_ROOT=${ADMIN_DOCUMENT_ROOT}
                - KONTROL_SERVERNAME=${KONTROL_SERVERNAME}
                - KONTROL_DOCUMENT_ROOT=${KONTROL_DOCUMENT_ROOT}
                - PAGOS_SERVERNAME=${PAGOS_SERVERNAME}
                - PAGOS_DOCUMENT_ROOT=${PAGOS_DOCUMENT_ROOT}
                - KAD_SERVERNAME=${KAD_SERVERNAME}
                - KAD_DOCUMENT_ROOT=${KAD_DOCUMENT_ROOT}
        image: kichink/apache-php
        ports:
            - "${APACHE_PORT}:80"
        volumes:
            - ${APPLICATIONS_PATH}:/var/www/html
        networks:
            - appnet
    node-utils:
        build:
            context: ./build/node-utils
            dockerfile: Dockerfile
        image: kichink/node-utils
        networks:
            - appnet
    redis:
        image: redis:alpine
        networks:
            - appnet
    db:
        image: mysql:5.6.35
        ports:
            - "${MYSQL_PORT}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ./db:/docker-entrypoint-initdb.d
            - data:/var/lib/mysql
        networks:
            - appnet
networks:
    appnet:
        driver: "bridge"
volumes:
    data:
        driver: "local"
